package bussotomation;


import DataBase.Busses;
import DataBase.Cities;
import DataBase.Customers;
import DataBase.Drivers;
import DataBase.Expeditions;
import SQL.SqlConnection;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Denizhan
 */

public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    DefaultTableModel tableDriverModel;
    DefaultTableModel tableExpeditionsModel;
    DefaultTableModel tableCustomerModel;
    DefaultTableModel tableBusModel;
    private int driverId;
   SQL.SqlConnection sql=new SqlConnection();
    
    
    
    public AdminScreen() {
        initComponents();
        setTitle("Yönetici Ekranı");
        tableBusModel=(DefaultTableModel) tableBus.getModel();
        tableExpeditionsModel=(DefaultTableModel) tableExpeditions.getModel();
        tableCustomerModel=(DefaultTableModel) tableCustomer.getModel();
        tableDriverModel=(DefaultTableModel) tableDriver.getModel();
        bringDriver();
        bringCustomer();
        comboBoxDriverCall();
        comboCityCall();
        bringBusses();
        bringExpedition();
        comboBoxBussCall();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfDriverName = new javax.swing.JTextField();
        buttonDriverAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfDriverAge = new javax.swing.JTextField();
        buttonDriverUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfDriverTelNum = new javax.swing.JTextField();
        tfDriverDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfDriverFind = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDriver = new javax.swing.JTable();
        labelDriverId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfadress = new javax.swing.JTextArea();
        tfcustomerName = new javax.swing.JTextField();
        tfcustomerTel = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        buttonSaveCustomer = new javax.swing.JButton();
        buttonDeleteCustomer = new javax.swing.JButton();
        buttonUpdateCustomer = new javax.swing.JButton();
        labelCustomerId = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfcustomerFind = new javax.swing.JTextField();
        labelGender = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        comboDriver = new javax.swing.JComboBox<>();
        tfbusPlate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfBusModel = new javax.swing.JTextField();
        butonBusAdd = new javax.swing.JButton();
        butonBusUpdate = new javax.swing.JButton();
        butonBusDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableBus = new javax.swing.JTable();
        labelDriverIdBuss = new javax.swing.JLabel();
        labenBussIdb = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxDeparture = new javax.swing.JComboBox<>();
        jComboBoxArrival = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEstimatedTime = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jComboBoxDate = new javax.swing.JComboBox<>();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jcomboHour = new javax.swing.JComboBox<>();
        jComboMinute = new javax.swing.JComboBox<>();
        buttonAddexpedition = new javax.swing.JButton();
        buttonDeleteexpedition = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableExpeditions = new javax.swing.JTable();
        bussComboChoose = new javax.swing.JComboBox<>();
        labelDeparture = new javax.swing.JLabel();
        labelArrival = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelDate = new javax.swing.JLabel();
        labelHour = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        labelExpNo = new javax.swing.JLabel();
        labelBussPlate = new javax.swing.JLabel();
        labelWarning = new javax.swing.JLabel();
        labelBusNo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        labelBussexpCheck = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFirstScreen = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Şöför Adı :");

        buttonDriverAdd.setText("Ekle");
        buttonDriverAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDriverAddActionPerformed(evt);
            }
        });

        jLabel6.setText("Şöför Yaşı :");

        buttonDriverUpdate.setText("Güncelle");
        buttonDriverUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDriverUpdateActionPerformed(evt);
            }
        });

        jLabel7.setText("Şöför Telefon :");

        tfDriverDelete.setText("Sil");
        tfDriverDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDriverDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("Arama :");

        tfDriverFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDriverFindKeyReleased(evt);
            }
        });

        tableDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Şöför No", "Söför İsim Soyisim", "Yaşı", "Telefonu"
            }
        ));
        tableDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDriverMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDriver);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDriverTelNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(tfDriverAge, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDriverAdd)
                            .addComponent(buttonDriverUpdate)
                            .addComponent(tfDriverDelete)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tfDriverFind, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(689, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonDriverAdd)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDriverUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(tfDriverDelete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfDriverAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfDriverTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfDriverFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Şöför", jPanel2);

        jLabel2.setText("Müşteri Adı Soyadı:");

        jLabel3.setText("Müşteri Telefonu :");

        jLabel5.setText("Müşteri Cinsiyeti :");

        jLabel14.setText("Müşteri Adresi :");

        tfadress.setColumns(20);
        tfadress.setRows(5);
        jScrollPane1.setViewportView(tfadress);

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın" }));

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri No", "Müşteri Ad Soyadı", "Cinsiyet", "Telefon No", "Adres"
            }
        ));
        tableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCustomer);

        buttonSaveCustomer.setText("Ekle");
        buttonSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveCustomerActionPerformed(evt);
            }
        });

        buttonDeleteCustomer.setText("Sil");
        buttonDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteCustomerActionPerformed(evt);
            }
        });

        buttonUpdateCustomer.setText("Güncelle");
        buttonUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateCustomerActionPerformed(evt);
            }
        });

        jLabel15.setText("Arama:");

        tfcustomerFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcustomerFindKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfcustomerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSaveCustomer)
                                    .addComponent(buttonDeleteCustomer)
                                    .addComponent(buttonUpdateCustomer))
                                .addGap(439, 439, 439))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tfcustomerFind, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfcustomerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonSaveCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdateCustomer)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfcustomerFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Müşteriler", jPanel1);

        jLabel18.setText("Plaka :");

        jLabel19.setText("Şöför :");

        comboDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDriverActionPerformed(evt);
            }
        });

        jLabel20.setText("Otobüs Markası :");

        butonBusAdd.setText("Ekle");
        butonBusAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBusAddActionPerformed(evt);
            }
        });

        butonBusUpdate.setText("Düzenle");
        butonBusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBusUpdateActionPerformed(evt);
            }
        });

        butonBusDelete.setText("Sil");
        butonBusDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBusDeleteActionPerformed(evt);
            }
        });

        tableBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Otobüs No", "Plaka", "Otobüs Markası", "Şöför"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBusMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableBus);

        labelDriverIdBuss.setText("jLabel21");

        labenBussIdb.setText("jLabel21");

        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboDriver, 0, 117, Short.MAX_VALUE)
                            .addComponent(tfbusPlate)
                            .addComponent(tfBusModel))
                        .addGap(18, 18, 18)
                        .addComponent(labelDriverIdBuss)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(butonBusAdd)
                                .addComponent(butonBusUpdate))
                            .addComponent(butonBusDelete)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(labenBussIdb, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel21)))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tfbusPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(tfBusModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDriverIdBuss))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(butonBusAdd)
                        .addGap(18, 18, 18)
                        .addComponent(butonBusUpdate)
                        .addGap(14, 14, 14)
                        .addComponent(butonBusDelete)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labenBussIdb, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Otobüsler", jPanel4);

        jLabel9.setText("Kalkış :");

        jLabel10.setText("Varış: ");

        jLabel11.setText("Saat :");

        jLabel12.setText("Otobüs :");

        jLabel16.setText("Tahmini Süre :");

        jLabel17.setText("Tutar :");

        jComboBoxDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDeparture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDepartureItemStateChanged(evt);
            }
        });

        jComboBoxArrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxArrival.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxArrivalItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tarih :");

        jComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDateActionPerformed(evt);
            }
        });

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OCAK", "ŞUBAT", "MART", "NİSAN", "MAYIS", "HAZİRAN", "TEMMUZ", "AĞUSTOS", "EYLÜL", "EKİM", "KASIM", "ARALIK", " " }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", " " }));
        jComboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYearActionPerformed(evt);
            }
        });

        jcomboHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jComboMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45", " ", " " }));

        buttonAddexpedition.setText("Seferlere kaydet");
        buttonAddexpedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddexpeditionActionPerformed(evt);
            }
        });

        buttonDeleteexpedition.setText("Sefer İptal");
        buttonDeleteexpedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteexpeditionActionPerformed(evt);
            }
        });

        tableExpeditions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sefer No", "Kalkış", "Varış", "Tarih", "Sefer Saati", "Otobüs No", "Tahmini Süre", "Kişi Başı Ücret", "Otobüs Plaka", "Şöför"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExpeditions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableExpeditionsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableExpeditions);

        bussComboChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bussComboChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bussComboChooseActionPerformed(evt);
            }
        });

        jButton1.setText("Tarih Onay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Saat Onay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sefer Oluştur (Önce tablodan seçim yapın)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(labelArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                                .addComponent(labelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
            .addComponent(jScrollPane5)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcomboHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelHour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelBussPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bussComboChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(buttonAddexpedition)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonDeleteexpedition)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(221, 221, 221)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelBussexpCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEstimatedTime)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labelDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jcomboHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelHour, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(bussComboChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBussPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldEstimatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonAddexpedition)
                                .addComponent(buttonDeleteexpedition))
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelExpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBussexpCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sefer Planla", jPanel3);

        jMenu1.setText("File");

        jMenuItemFirstScreen.setText("İlk Ekran");
        jMenuItemFirstScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFirstScreenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFirstScreen);

        jMenuItemQuit.setText("Çıkış");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Yenile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDateActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxDateActionPerformed

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    private void jComboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxYearActionPerformed

    private void jMenuItemFirstScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFirstScreenActionPerformed
        // TODO add your handling code here:
        Apps appScrees=new Apps();
        setVisible(false);
        appScrees.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemFirstScreenActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void buttonDriverAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDriverAddActionPerformed
        // TODO add your handling code here:
        String driverName=tfDriverName.getText();
        int driverAge=Integer.valueOf(tfDriverAge.getText());
        String driverTel=tfDriverTelNum.getText();
         sql.driverAdd(driverName,driverAge,driverTel);
         bringDriver();
    }//GEN-LAST:event_buttonDriverAddActionPerformed

    private void tfDriverFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDriverFindKeyReleased
        // TODO add your handling code here:
        String find=tfDriverFind.getText();
        dynamicFindDriver(find);
    }//GEN-LAST:event_tfDriverFindKeyReleased

    private void buttonDriverUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDriverUpdateActionPerformed
        // TODO add your handling code here:
       
        
        int driverNo=Integer.valueOf(labelDriverId.getText());
        String driverName=tfDriverName.getText();
        int driverAge=Integer.valueOf(tfDriverAge.getText());
        String driverTel=tfDriverTelNum.getText();
        sql.driverChange(driverNo, driverName, driverAge, driverTel);
        bringDriver();
    }//GEN-LAST:event_buttonDriverUpdateActionPerformed

    private void tableDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDriverMouseClicked
        // TODO add your handling code here:
          int selectedRow= tableDriver.getSelectedRow();
        //int selectedColumn=tableDriver.getSelectedColumn();
        tfDriverName.setText(tableDriver.getValueAt(selectedRow,1).toString());
                tfDriverAge.setText(tableDriver.getValueAt(selectedRow,2).toString());
                tfDriverTelNum.setText(tableDriver.getValueAt(selectedRow,3).toString());
                        
        labelDriverId.setText(tableDriver.getValueAt(selectedRow,0).toString());
        
        
    }//GEN-LAST:event_tableDriverMouseClicked

    private void tfDriverDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDriverDeleteActionPerformed
        // TODO add your handling code here:
        int driverNo=Integer.valueOf(labelDriverId.getText());
       sql.driverDelete(driverNo);
       bringDriver();
    }//GEN-LAST:event_tfDriverDeleteActionPerformed

    private void buttonSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveCustomerActionPerformed
        // TODO add your handling code here:
        String customerName=tfcustomerName.getText();
        String customerTel=tfcustomerTel.getText();
        String customerGender=(String) comboGender.getSelectedItem();
        String customerAdress=tfadress.getText();
        sql.customerAdd(customerName, customerGender, customerTel, customerAdress);
        bringCustomer();
        
    }//GEN-LAST:event_buttonSaveCustomerActionPerformed

    private void buttonUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateCustomerActionPerformed
        // TODO add your handling code here:
        int customerId=Integer.valueOf(labelCustomerId.getText());
        String customerName=tfcustomerName.getText();
        String customerTel=tfcustomerTel.getText();
        String customerGender=(String) comboGender.getSelectedItem();
        String customerAdress=tfadress.getText();
        sql.customerChange(customerId, customerName, customerGender, customerTel, customerAdress);
        bringCustomer();
        
    }//GEN-LAST:event_buttonUpdateCustomerActionPerformed

    private void tableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomerMouseClicked
        // TODO add your handling code here:
         int selectedRow= tableCustomer.getSelectedRow();
        //int selectedColumn=tableDriver.getSelectedColumn();
        labelGender.setText(tableCustomer.getValueAt(selectedRow,2).toString());
         labelCustomerId.setText(tableCustomer.getValueAt(selectedRow,0).toString());
        tfcustomerName.setText(tableCustomer.getValueAt(selectedRow,1).toString());
        comboGender.setActionCommand(tableCustomer.getValueAt(selectedRow,2).toString());
        tfcustomerTel.setText(tableCustomer.getValueAt(selectedRow,3).toString());
         tfadress.setText(tableCustomer.getValueAt(selectedRow,4).toString());
        
       // comboGender.setOtableCustomer.getValueAt(selectedRow,0).toString());
     
     
        
        
    }//GEN-LAST:event_tableCustomerMouseClicked

    private void tfcustomerFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcustomerFindKeyReleased
        // TODO add your handling code here:
        String find=tfcustomerFind.getText();
        dynamicFindCustomer(find);
        
    }//GEN-LAST:event_tfcustomerFindKeyReleased

    private void buttonDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteCustomerActionPerformed
        // TODO add your handling code here:
        int customerId=Integer.valueOf(labelCustomerId.getText());
        sql.customerDelete(customerId);
        bringCustomer();
        
    }//GEN-LAST:event_buttonDeleteCustomerActionPerformed

    private void butonBusAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBusAddActionPerformed
        // TODO add your handling code here:
        String bussPllate=tfbusPlate.getText();
        String bussModel=tfBusModel.getText();
        String driverName=labelDriverIdBuss.getText();
        int driverNo=sql.getDriverId(driverName);
        labelDriverIdBuss.setText(String.valueOf(driverNo));
        sql.bussAdd(bussPllate, bussModel, driverNo);
        bringBusses();
        
        
        System.out.println(driverNo);
    }//GEN-LAST:event_butonBusAddActionPerformed

    private void comboDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDriverActionPerformed
        // TODO add your handling code here:
        labelDriverIdBuss.setText(String.valueOf(comboDriver.getSelectedItem()));
        
    }//GEN-LAST:event_comboDriverActionPerformed

    private void butonBusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBusUpdateActionPerformed
        // TODO add your handling code here:
        String driverName=labelDriverIdBuss.getText();
        int driverNoNew=sql.getDriverId(driverName);
        labelDriverIdBuss.setText(String.valueOf(driverNoNew));
        int busNo=Integer.valueOf(jLabel21.getText());
        String bussPlate=tfbusPlate.getText();
        String bussModel=tfBusModel.getText();
        sql.bussUpdate(bussPlate, bussModel, driverNoNew, busNo);
        bringBusses();
        
        
       
    }//GEN-LAST:event_butonBusUpdateActionPerformed

    private void tableBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBusMouseClicked
        // TODO add your handling code here:
        int selectedRow=tableBus.getSelectedRow();
        System.out.println(tableBus.getValueAt(selectedRow,0).toString());
        jLabel21.setText(tableBus.getValueAt(selectedRow,0).toString());
        tfbusPlate.setText(tableBus.getValueAt(selectedRow,1).toString());
        tfBusModel.setText(tableBus.getValueAt(selectedRow,2).toString());
        labelDriverIdBuss.setText(tableBus.getValueAt(selectedRow,3).toString());
        
    }//GEN-LAST:event_tableBusMouseClicked

    private void butonBusDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonBusDeleteActionPerformed
        // TODO add your handling code here:
        int busNo=Integer.valueOf(jLabel21.getText());
        sql.bussDelete(busNo);
        bringBusses();
    }//GEN-LAST:event_butonBusDeleteActionPerformed

    private void buttonAddexpeditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddexpeditionActionPerformed
        // TODO add your handling code here:
        
        String arrivalCity=labelArrival.getText();
        String departureCity=labelDeparture.getText();
        int departure=sql.getCityId(departureCity);//++
        int arrival=sql.getCityId(arrivalCity);//++
        String date=labelDate.getText();//+
        String hour=labelHour.getText();//+
         String busPlate=labelBussPlate.getText();
       int busNo=sql.getBusId(busPlate);
        String sestTime=jTextFieldEstimatedTime.getText();
        String sprice=jTextFieldPrice.getText();
             
        int estTime=Integer.valueOf(sestTime);//+
        int price=Integer.valueOf(sprice);//+
        System.out.println(busPlate);
        sql.addExpedition(departure, arrival, date, hour, busNo, estTime, price);
        bringExpedition();
        
        
        
        //int bussId=sql.getBusId();
        
        
        
        
    }//GEN-LAST:event_buttonAddexpeditionActionPerformed

    private void bussComboChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bussComboChooseActionPerformed
        // TODO add your handling code here:
       labelBussPlate.setText(String.valueOf(bussComboChoose.getSelectedItem()));
      
       
    }//GEN-LAST:event_bussComboChooseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        bringDriver();
        bringCustomer();
        comboBoxDriverCall();
        bringBusses();
        bringExpedition();
        comboBoxBussCall();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBoxDepartureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDepartureItemStateChanged
        // TODO add your handling code here:
     labelDeparture.setText((String) jComboBoxDeparture.getSelectedItem());
    }//GEN-LAST:event_jComboBoxDepartureItemStateChanged

    private void jComboBoxArrivalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxArrivalItemStateChanged
        // TODO add your handling code here:
        labelArrival.setText((String) jComboBoxArrival.getSelectedItem());
    }//GEN-LAST:event_jComboBoxArrivalItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String day=(String)jComboBoxDate.getSelectedItem();
        String month=(String)jComboBoxMonth.getSelectedItem();
        String year=(String)jComboBoxYear.getSelectedItem();
        String date=day+"/"+month+"/"+year;
        labelDate.setText(date);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String hour=(String)jcomboHour.getSelectedItem()+":"+(String)jComboMinute.getSelectedItem();
        labelHour.setText(hour);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableExpeditionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableExpeditionsMouseClicked
        // TODO add your handling code here:
        int selectedRow=tableExpeditions.getSelectedRow();
        labelExpNo.setText(tableExpeditions.getValueAt(selectedRow,0).toString());
        labelDeparture.setText(tableExpeditions.getValueAt(selectedRow,1).toString());
        labelArrival.setText(tableExpeditions.getValueAt(selectedRow,2).toString());
         labelDate.setText(tableExpeditions.getValueAt(selectedRow,3).toString());
          labelHour.setText(tableExpeditions.getValueAt(selectedRow,4).toString());
           labelBusNo.setText(tableExpeditions.getValueAt(selectedRow,5).toString());
            jTextFieldEstimatedTime.setText(tableExpeditions.getValueAt(selectedRow,6).toString());
             jTextFieldPrice.setText(tableExpeditions.getValueAt(selectedRow,7).toString());
           labelBussPlate.setText(tableExpeditions.getValueAt(selectedRow,8).toString());
    }//GEN-LAST:event_tableExpeditionsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int expNo=Integer.valueOf(labelExpNo.getText());
        System.out.println(expNo+"ad");
        boolean bussExpCheck=sql.bussExpCheck(expNo);
        if(bussExpCheck==true){
           labelBussexpCheck.setText("Aynı Seferden Oluşturulmuş veya veri tabanı hatası");  
        }else{
        sql.addBussExp(expNo);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonDeleteexpeditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteexpeditionActionPerformed
        // TODO add your handling code here:
       int expId=Integer.valueOf(labelExpNo.getText());
       sql.deleteExpedition(expId);
       sql.deleteBussSeat(expId);
       bringExpedition();
    }//GEN-LAST:event_buttonDeleteexpeditionActionPerformed

    /**
     * @param args the command line arguments
     */
  
    //------------------------- driver bringer and driver search-------------------------------------
    public void bringDriver(){
        tableDriverModel.setRowCount(0);
        ArrayList<Drivers> drivers=new ArrayList<Drivers>();
        drivers=sql.driverCome();
        if(drivers!=null){
            for(Drivers driver:drivers){
                Object[] addRow={driver.getDriverNo(),driver.getDriverName(),driver.getDriverAge(),driver.getDriverTel()};
            tableDriverModel.addRow(addRow);
            }
         }
    }
    public void dynamicFindDriver(String find){
         TableRowSorter<DefaultTableModel>tf=new TableRowSorter<>(tableDriverModel);
      tableDriver.setRowSorter(tf);
      tf.setRowFilter(RowFilter.regexFilter(find));
        
    }
    //---------------CUSTOMER BRİNG AND FİNF---------------------------
    public void bringCustomer(){
        tableCustomerModel.setRowCount(0);
        ArrayList<Customers>customers=new ArrayList<Customers>();
        customers=sql.bringCustomer();
        if(customers!=null){
            for(Customers customer:customers){
                Object []addRow={customer.getCustomerId(),customer.getCstomerName(),customer.getGender(),customer.getTelNo(),customer.getAdress()};
                tableCustomerModel.addRow(addRow);
                
               
            }
         
        }
    }
    public void dynamicFindCustomer(String find){
        TableRowSorter<DefaultTableModel>tf=new TableRowSorter<>(tableCustomerModel);
        tableCustomer.setRowSorter(tf);
        tf.setRowFilter(RowFilter.regexFilter(find));
        
    }
    //-------------------- BUSS SCREEN ------------------------------
    public void comboBoxDriverCall(){
        comboDriver.removeAllItems();
        ArrayList<Drivers>drivers=new ArrayList<Drivers>();
        drivers=sql.driverCome();
        if(drivers!=null){
            for(Drivers driver:drivers){
               // Object []addCombo={driver.getDriverName()};
               
                comboDriver.addItem(driver.getDriverName());
            }
        }
    }
    public void bringBusses(){
        tableBusModel.setRowCount(0);
        ArrayList<Busses>busses=new ArrayList<Busses>();
        busses=sql.bringBusses();
        if(busses!=null){
            for(Busses bus:busses){
               Object []add={bus.getBussNo(),bus.getBussPlate(),bus.getBussModel(),bus.getDriverName()}; 
               
               tableBusModel.addRow(add);
            }
        }
    }
    //----------------EXPEDİTİON SCREEN-------------------------
    public void bringExpedition(){
        tableExpeditionsModel.setRowCount(0);
        ArrayList<Expeditions>expeditions=new ArrayList<Expeditions>();
        expeditions=sql.bringExpeditions();
        if(expeditions!=null){
            for(Expeditions exped:expeditions){
                Object []add={exped.getExNo(),exped.getDeparture(),exped.getArrival(),exped.getDate(),exped.getHour(),exped.getBussNo(),exped.getTime(),exped.getPrice(),exped.getBussPlate(),exped.getBussDriver()};
                tableExpeditionsModel.addRow(add);
            }
        }
    }
    public void comboBoxBussCall(){
        bussComboChoose.removeAllItems();
        ArrayList<Busses>busses=new ArrayList<Busses>();
        busses=sql.bringBusses();
        if(busses!=null){
            for(Busses bus:busses){
               // Object []addCombo={driver.getDriverName()};
               
               bussComboChoose.addItem(bus.getBussPlate());
            }
        }
    }
    public void comboCityCall(){
        jComboBoxDeparture.removeAllItems();
        jComboBoxArrival.removeAllItems();
        ArrayList<Cities>cities=new ArrayList<Cities>();
        cities=sql.bringCity();
        if(cities!=null){
            for(Cities city:cities){
               // Object []addCombo={driver.getDriverName()};
               jComboBoxDeparture.addItem(city.getCityName());
               jComboBoxArrival.addItem(city.getCityName());
               labelDeparture.setText(jComboBoxDeparture.getSelectedItem().toString());
               labelArrival.setText(jComboBoxArrival.getSelectedItem().toString());
            }
        }
    }
    
        
    

        
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bussComboChoose;
    private javax.swing.JButton butonBusAdd;
    private javax.swing.JButton butonBusDelete;
    private javax.swing.JButton butonBusUpdate;
    private javax.swing.JButton buttonAddexpedition;
    private javax.swing.JButton buttonDeleteCustomer;
    private javax.swing.JButton buttonDeleteexpedition;
    private javax.swing.JButton buttonDriverAdd;
    private javax.swing.JButton buttonDriverUpdate;
    private javax.swing.JButton buttonSaveCustomer;
    private javax.swing.JButton buttonUpdateCustomer;
    private javax.swing.JComboBox<String> comboDriver;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxArrival;
    private javax.swing.JComboBox<String> jComboBoxDate;
    private javax.swing.JComboBox<String> jComboBoxDeparture;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JComboBox<String> jComboMinute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemFirstScreen;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldEstimatedTime;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JComboBox<String> jcomboHour;
    private javax.swing.JLabel labelArrival;
    private javax.swing.JLabel labelBusNo;
    private javax.swing.JLabel labelBussPlate;
    private javax.swing.JLabel labelBussexpCheck;
    private javax.swing.JLabel labelCustomerId;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDeparture;
    private javax.swing.JLabel labelDriverId;
    private javax.swing.JLabel labelDriverIdBuss;
    private javax.swing.JLabel labelExpNo;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHour;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JLabel labenBussIdb;
    private javax.swing.JTable tableBus;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTable tableDriver;
    private javax.swing.JTable tableExpeditions;
    private javax.swing.JTextField tfBusModel;
    private javax.swing.JTextField tfDriverAge;
    private javax.swing.JButton tfDriverDelete;
    private javax.swing.JTextField tfDriverFind;
    private javax.swing.JTextField tfDriverName;
    private javax.swing.JTextField tfDriverTelNum;
    private javax.swing.JTextArea tfadress;
    private javax.swing.JTextField tfbusPlate;
    private javax.swing.JTextField tfcustomerFind;
    private javax.swing.JTextField tfcustomerName;
    private javax.swing.JTextField tfcustomerTel;
    // End of variables declaration//GEN-END:variables
}
